### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by JiewenKuang** [navamikairanda/phi_sft#1]
Thank you very much for publishing the code of this work.
But I can't seem to compile on my work computer.
My computer is Centos and the compiler is GCC7.3.
The error message is shown in the picture:
`cc -c -O3 -Wall -fPIC -std=c99   -DMACHTYPE_ -I src/ -I build/linux/ -I external/src/   \
  progs/taucs_cilk_test.c \
  -oobj/linux/taucs_cilk_test.o
progs/taucs_cilk_test.c:8:10: fatal error：cilk.h：
No such file or directory
    8 | #include <cilk.h>
      |          ^~~~~~~~。`
How can I find click correctly？ 
I am looking forward to your reply, thank you!

**Comment by JiewenKuang** [comment]
had solved

**Comment by qianyuling-wl** [comment]
> had solved

Sorry to bother you, could you please ask how you solved it? I have also encountered this problem. My GCC version is 9.8, but I cannot solve it. Could you help me? Thank you very much
